BEGIN;

ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS company TEXT,
    ADD COLUMN IF NOT EXISTS lead_type TEXT,
    ADD COLUMN IF NOT EXISTS entry_path TEXT,
    ADD COLUMN IF NOT EXISTS extra_json JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMIT;
